### ISSUE TITLE
Update shebang to use perl binary from user PATH 

### ISSUE THREAD

**Issue by atoomic** [Tux/App-ccdiff#1]
As shown there 
https://github.com/Tux/App-ccdiff/blob/75b1a10d58b63336504cd69226887fad07479c51/ccdiff#L1
``
!/pro/bin/perl
``

might be an issue for releasing it, I would suggest a more traditional 
```
#!/usr/bin/env perl
```

**Comment by Tux** [comment]
Changed

Personally I am not a fan of env, but most people like it.
Env completely fails if you are testing an uninstalled perl and have the $PATH set to find that perl first: *NO* modules are available and the tool that has env in the shebang will fail
