### ISSUE TITLE
documentation: ccdiff for "git diff" command

### ISSUE THREAD

**Issue by ufobat** [Tux/App-ccdiff#10]
I am using `git diff` before I commit a change. So I wanted to have ccdiff for this output as well.

My first approch was `$ git config --global diff.external ccdiff` which is not working correctly because the diff output is the other way around. What I was about to add in my commit is displayed as being removed. A wrapper script would probably fix that.

I noticed that you can use `git difftool` instead of `git diff`. So I am going to change my git aliases. Maybe it's worth documenting this so users dont need to google this again.

**Comment by Tux** [comment]
Part of it was already in the docs, but I just extended it. https://github.com/Tux/App-ccdiff/blob/master/ccdiff + https://github.com/Tux/App-ccdiff/blob/master/Files/git-ccdiff
