### ISSUE TITLE
Wishlist: Add support for GNU diff's -r  (--recursive) and -p (--show-c-function) options

### ISSUE THREAD

**Issue by raforg** [Tux/App-ccdiff#17]
Hi, It would be great if ccdiff supported more of GNU diff's options (i.e. the ones I use all the time). :-)
Particularly -r (--recursive) and -p (--show-c-function).

**Comment by Tux** [comment]
`-r / --recursive` was on my own wishlist, but as `ccdiff` might be slow on big files, I just didn't implement that (yet)

**Comment by Tux** [comment]
For `-p`, I would (for now) say: "Patches welcome"

**Comment by Tux** [comment]
As for `-p` that won't merge, as that was/is already in use for `--pink` (requested on th TPC where this was presented)
Would you still use it if only supported on the long for `--show-c-function`?

**Comment by Tux** [comment]
(Automatic) recursiveness has been implemented in commit fa60e346c0fa456f9cb372de085652958f91e858
I close this issue. If you still want to implement `--show-c-function` feel free to do a PR
