### ISSUE TITLE
Should have more error messages

### ISSUE THREAD

**Issue by raforg** [Tux/App-ccdiff#18]
Hi, if ccdiff is invoked with invalid command line options (e.g. --no-colors --no-colo), there is no error message about it. There is also no error message if either of the file arguments supplied is a directory rather than file. Error messages when encountering incorrect usage would be very helpful.

**Comment by Tux** [comment]
```
$ ccdiff --flubber x u
Unknown option: flubber
:
```
All options that are not reported as such are valid. Read the docs of Getopt::Long
An error message for folders, block- and character devices and other imposibilities seems a goot idea. For now: just don't do that.

**Comment by raforg** [comment]
Thanks. Clearly, Getopt::Long is smarter than I expected. :-)

**Comment by Tux** [comment]
Warnings were added in 936d48677e31fc797b3bf14827f271e1a170196c and 936d48677e31fc797b3bf14827f271e1a170196c
