### ISSUE TITLE
Too slow on large files (even if almost identical)

### ISSUE THREAD

**Issue by raforg** [Tux/App-ccdiff#19]
Hi, ccdiff took 6m19s on two files that were ~41K lines long. GNU diff took 0.01s on the same hardware (diff -durp output was 119 lines). Is there any chance that ccdiff could be made to be reasonably fast? If it's because Algorithm::Diff is slow, and there's nothing you can do about that, you might consider adding the ability for ccdiff to operate by invoking GNU diff and scanning its output, and performing the horizontal diff on the lines reported as being different by GNU diff. Then Algorithm::Diff wouldn't have to analyse the entire files. Just a thought.

**Comment by Tux** [comment]
Did you profile?
`ccdiff` will be (very) slow if changes occur in (very) long lines. 41k is not too big, but if it is a single line, it will hurt. I think this was never meant for that.

**Comment by Tux** [comment]
```
$ ls -l foo1 foo2
-rw-rw-r-- 1 merijn users 520000 Sep 14 15:15 foo1
-rw-rw-r-- 1 merijn users 520000 Sep 14 15:16 foo2
$ time diff foo1 foo2
39910c39910
< aaaaaaabaaaa
---
> aaaaaaacaaaa
0.001u 0.000s 0:00.00 0.0%      0+0k 0+0io 0pf+0w
$ time ccdiff foo1 foo2
< foo1    Mon Sep 14 15:15:57 2020
> foo2    Mon Sep 14 15:16:26 2020
39910,39910c39910,39910
< aaaaaaabaaaa
---
> aaaaaaacaaaa
0.080u 0.008s 0:00.08 100.0%    0+0k 0+0io 0pf+0w
```
Not too bad. Those are 500k files with one small change

**Comment by Tux** [comment]
Two 50k files with just one line and just one character difference
```
$ ll foo1 foo2
918295247 -rw-rw-r-- 1 merijn users 50001 2020-09-14 15:48:05 foo1
918295249 -rw-rw-r-- 1 merijn users 50001 2020-09-14 15:47:58 foo2
$ time diff foo1 foo2 >/dev/null
0.001u 0.000s 0:00.00 0.0%      0+0k 0+0io 0pf+0w
$ time ccdiff foo1 foo2 > /dev/null
0.137u 0.015s 0:00.15 93.3%     0+0k 0+0io 0pf+0w
```
Yes, notable slower, but 0.1 second is not something I worry about

**Comment by raforg** [comment]
The files I ccdiff'd differed by having 2 separate lines added near the top of the file, and 86 lines added very close to the end of the file. There were about 20 (unchanged) lines that were over 400 characters long, but the rest were much shorter.

I profiled it with Devel::NYTProf but the resulting nytprof.out file was about 18GB. I haven't got the necessary things installed to analyse it but I've bzipped it for you if you want to download it, but it's 629MB bzip2'd:

    http://raf.org/tmp/nytprof.out.bz2

If that's too much to download(!) you can have the input files themselves and profile it locally:

    http://raf.org/tmp/ccdiff.in.a.bz2 (32KB)
    http://raf.org/tmp/ccdiff.in.b.bz2 (32KB)

I hope that's helpful.

**Comment by Tux** [comment]
[Image](https://tux.nl/Files/App-ccdiff-NYTProf.png) makes it pretty obvious. (because your perl conf differs from mine, I had to re-run it: over 2 hours to generate a 2.4 Gb log)
```
Top 15 Subroutines
               Excl    Incl
    calls P F  time    time    Subroutine
--------- - - ------- ------- ---------------------------------------------------------------------
100751848 1 1   712 s   712 s  Algorithm::Diff::_replaceNextLargerWith
        1 1 1   385 s  1097 s  Algorithm::Diff::_longestCommonSubsequence
        1 1 1  93.3ms   104ms  Algorithm::Diff::_withPositionsOfInInterval
        9 4 1  71.2ms  79.1ms      App::ccdiff::CORE:readline (opcode)
    80824 2 1  62.6ms  62.6ms  Algorithm::Diff::__ANON__[Algorithm/Diff.pm:152]
        6 6 6  61.8ms   201ms         XSLoader::load (recurses: max depth 1, inclusive time 18.5ms)
        1 1 1  54.7ms   231ms           PerlIO::import
        5 2 1  41.7ms  57.5ms      App::ccdiff::CORE:prtf (opcode)
        1 1 1  35.7ms  36.9ms           Encode::BEGIN@53
        1 1 1  33.0ms  70.6ms           Encode::BEGIN@56
        1 1 1  32.2ms  56.6ms        charnames::BEGIN@5
        1 1 1  30.6ms   158ms       DynaLoader::BEGIN@111
        1 1 1  27.1ms  29.5ms      App::ccdiff::BEGIN@8
        1 1 1  24.4ms  24.4ms        charnames::BEGIN@578
        1 1 1  22.0ms   136ms      App::ccdiff::BEGIN@7
```

**Comment by raforg** [comment]
That looks nasty. The comments do say that _replaceNextLargerWith is where 75% of the time is spent (so make it fast). :-)
It's just a binary search. Or rather, 100 million binary searches. :-)

But there's good news. There's an Algorithm::Diff::XS module that says it's a drop-in replacement for Algorithm::LCS (which no longer seems to exist - perhaps it's an old name for Algorithm::Diff). Inside, it says that it's a replacement for Algorithm::Diff. So I installed it, changed ccdiff to use it, and now it only takes 7.5s. That's still much slower than diff in relative terms, but it's fine, really.

Here's a rubbish little patch, just to ccdiff itself, not to any package metadata. You might want to make it able to use Algorithm::Diff::XS if it's available, and use Algorithm::Diff otherwise. I don't know how to make that happen.

[ccdiff.xs.patch.txt](https://github.com/Tux/App-ccdiff/files/5229012/ccdiff.xs.patch.txt)

cheers,
raf

**Comment by Tux** [comment]
I have made that dynamic in [da264739c99c3cc3d043bd7b428670d6166ea191]

**Comment by raforg** [comment]
That looks great. Thanks.
