### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by gregoa** [Tux/App-ccdiff#2]
The LICENSE file is Artistic-2.0, and README.md says "The Artistic License 2.0".
OTOH, ccdiff and lib/App/ccdiff.pm say "same terms as Perl" which expands to "Artistic or GPL-1+".

Please clarify which license ccdiff is actually released under; both options are fine just not the contradiction :)

Cheers,
gregor, considering to package ccdiff for Debian after coming home from TPCiG

**Comment by Tux** [comment]
[IANAL] Fixed. If this is still not OK, I'd like to see a PR :)

**Comment by gregoa** [comment]
Looks perfectly fine, thanks!

(The last aesthetic wrinkle is that Makefile.PL still has ``LICENSE            => "perl",`` which should probably be ``LICENSE            => "artistic_2",`` but this doesn't seem to have any effect on the actual license grant texts in the files. Also META.{json,yml} have a ``license`` key.)

Cheers,
gregor

**Comment by Tux** [comment]
Thanks, done
