### ISSUE TITLE
git ccdiff . fails

### ISSUE THREAD

**Issue by ryandesign** [Tux/App-ccdiff#25]
I have configured git as indicated in the App-ccdiff documentation so that `git ccdiff` should work. What I was expecting was that `git ccdiff ...` would work like `git diff ...` but with better coloring.

`git ccdiff` (and `git diff`) by itself works: it shows me all the diffs in my git clone. But I only want to see the diffs for the current directory. `git diff .` shows me that, however `git ccdiff .` fails:

```
$ git ccdiff .
fatal: ambiguous argument '.~1...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by Tux** [comment]
Interesting. I am not a git expert, so I'd say `patches welcome`.
(at the moment I really have no idea how to fix that)

**Comment by Tux** [comment]
FWIW, this comes from `git-ccdiff`, which is far from perfect as you just proved.
I've just pushed a new version. Please check if that new version better meets your expectations.

**Comment by Tux** [comment]
No feedback in 1½ years. Closing
