### ISSUE TITLE
Permissions of rc file

### ISSUE THREAD

**Issue by gregoa** [Tux/App-ccdiff#5]
Is there a specific reason why the config has to be 755? If yes, please mention the requirement in the documentation.
(It just took me some time to figure out why my config was ignored, which had 775, until I read the code ...)

Cheers,
gregor

**Comment by Tux** [comment]
It is in the manual/pod:
```
       Option files are only read and evaluated if it is not empty and not
       writeable by others than the owner.
```
It is a security feature. In this tool, options are not destructive, but I've seen tools where config files writable by non-owner may lead to destruction.
(typo in manual already fixed)

**Comment by gregoa** [comment]
On Sun, 19 Aug 2018 03:01:45 -0700, H.Merijn Brand wrote:

> It is in the manual/pod:
> ```
>        Option files are only read and evaluated if it is not empty and not
>        writeable by others than the owner.
> ```

Oops, seems I was a bit too tired yesterday night. Sorry for missing
this.

> It is a security feature. In this tool, options are not
> destructive, but I've seen tools where config files writable by
> non-owner may lead to destruction.

Right.


Thanks for all the other fixes and the new release!
I'll upload ccdiff to Debian later today.


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Leonard Cohen: Diamonds In The Mine
