### ISSUE TITLE
support  fordefault background/foreground colors

### ISSUE THREAD

**Issue by ufobat** [Tux/App-ccdiff#7]
I am working on the default ubuntu terminal, with system default color theming. For ccdiff I don't use the `-r` reverse option, so I want to see the (foreground) color red or green for my changes. But I'd still like to see my default background color. 

ccdiff defaults the background color to "white" and it is not possible to say `--bg=''`.
If you invoke ccdiff with `--bg="rubbish"` I would  get the expected behaviour, the background color is untouched. But I am getting this 2 warnings as well:

```
Use of uninitialized value in concatenation (.) or string at /home/martin/perl5/perlbrew/perls/perl-5.26.0/bin/ccdiff line 102.
Use of uninitialized value in concatenation (.) or string at /home/martin/perl5/perlbrew/perls/perl-5.26.0/bin/ccdiff line 104.
```

I am not sure if this applies to the foreground color settings as well, if you turn on `-r`

**Comment by Tux** [comment]
I had to read that a few times before I understood what you were asking, but I now get it. I will implement the color "none" and also add some warnings and checks for the use of unsupported colors.

**Comment by Tux** [comment]
Now pushed. Color `none` is now a valid choice (also in your `~/.config/ccdiff`) and undefined colors are now more prohibited

**Comment by ufobat** [comment]
sorry and thank you :+1:
