### ISSUE TITLE
colors for +|- or <|>

### ISSUE THREAD

**Issue by ufobat** [Tux/App-ccdiff#8]
The Command `git log -p` displays the `+` or `-` in front of new or deleted lines in the appropriate color. If ccdiff could display those chars in color it would be easier to see added/removed empty lines.

**Comment by Tux** [comment]
Done and pushed. Feel free to check.
While checking, I noticed that `diff --color` also shows the prefixes in the appropriate colors.

**Comment by ufobat** [comment]
the + and - are colored, but the text isn't:

https://gist.github.com/ufobat/30a4cd45430a9c566b4ab680f694b0a3#file-ccdif_0-23_prerelease-png
