### ISSUE TITLE
when subdiff makes no sense

### ISSUE THREAD

**Issue by ufobat** [Tux/App-ccdiff#9]
I've got the feeling that subdiff()ing doesn't make sense for all circumstances.

In my example I was diffing those 2 texts:

```
   X::NYI.new(feature => 'snappy compression').throw
```
```
    # read-varint updates $!position
    my $replace-position = $!position;

    my Int $compressed-length = self!read-varint();
    my Blob $compressed =$!data.subbuf($!position, $compressed-length );
    my Blob $uncompressed = Compress::Zlib::uncompress( $compressed );

    # update date and length
    # position should not change
    $!position = $replace-position;
    $!data.subbuf-rw($replace-position, $compressed-length) = $uncompressed;
    $!size = $!data.elems;
```

The largest chunk that both text samples have in common is the string `compress`. There are a lot of small one-character sized chunks that are not highlighted as a change. For a humanit is clear to see that one text sample replaces the other completly.

I am wondering wether it makes sense to have some kind of heuristics that decides if a subdiff of a chunk is so fundamental different to the other that you rather not display the common chunks (like a linewise diff does)?

**Comment by Tux** [comment]
Care to test https://github.com/Tux/App-ccdiff/commit/c241f206810a8f3e8c886b7c49f47e374087a2a9 ?

**Comment by ufobat** [comment]
I think it works as expected :)

**Comment by ufobat** [comment]
I would argue that the threshold is not a DWIM feature, because one could easily create an example that avoids subdiff()ing though it still makes sense. E.g:

[matrix1.txt](https://github.com/Tux/App-ccdiff/files/2316032/matrix1.txt)
[matrix4.txt](https://github.com/Tux/App-ccdiff/files/2316033/matrix4.txt)

 I would still like to keep the threshold feature, because it allows the user to influence the decission wether you have a subdiff or not, still i'd suggest to set the default to `0` so you have predictable results. 

I'd suggest to have some kind of heuristics that decides if you have to much small parts that you actually keep VS a lot of larger changes (which is the case in my example of my first post).

My example in PR #12 creates 2 histograms (and is not using them), because you might whan to have a more sofisticated implementation of `skip_subdiff_heuristics`. This PR works with the initial example as well as with the matrix example. Again, I'd suggest that this heuristics is turned off by default in favor of predictable results.

**Comment by Tux** [comment]
When I fetch them, both are equal, so I cannot use them to make up an opinion

**Comment by Tux** [comment]
Could you pull and play with `-h 20` (where 20 is a percentage)?
You can put it in `~/.config/ccdiff` as `heuristics: 20`
It defaults to `0`, which means to not apply heuristics.
